#!/bin/bash
for (( i=1; i <= $1 ; i++ ))
do
echo "test $i"
node textCreator.js > /dev/null;
node script.js input.txt /e e.txt > /dev/null;
node script.js e.txt /d output.txt > /dev/null;
cmp input.txt output.txt
done
